Azure/azure-storage-fuse

- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
- blobfuse/blobfuse.cpp
It's pretty hard to debug errno=1600
> Print exception info

- azure-storage-cpp-lite/src/base64.cpp
- blobfuse/blobfuse.h
- blobfuse/directoryapis.cpp
- blobfuse/fileapis.cpp
- blobfuse/utilities.cpp
1. fixed conversion of sizes to strings
2. fixed build for unsinged char (arm32)
> Fix build on 32 bit architectures

- blobfuse/blobfuse.h
- blobfuse/fileapis.cpp
- blobfuse/tests.py
- blobfuse/utilities.cpp
> Fix issue 57 - take shared flock on the file

- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
> Increase min block_size to 16mb, and handle blobs up to 4.77TB

- azure-storage-cpp-lite/include/executor.h
- azure-storage-cpp-lite/include/http/libcurl_http_client.h
- azure-storage-cpp-lite/include/http_base.h
- azure-storage-cpp-lite/include/storage_stream.h
- azure-storage-cpp-lite/src/http/libcurl_http_client.cpp
1. Restored state of CurlEasyRequest after initial 503
2. Added handling of curl errors
> Fix retry logic for download

- blobfuse/blobfuse.cpp
- blobfuse/blobfuse.h
- blobfuse/directoryapis.cpp
- blobfuse/fileapis.cpp
- blobfuse/utilities.cpp
This adds log statements throughout the blobfuse part of the codebase.  Cpplite will be done separately.
> Changing blobfuse to log to syslog

- CMakeLists.txt
- azure-storage-cpp-lite/include/constants.dat
- azure-storage-cpp-lite/include/storage_credential.h
- azure-storage-cpp-lite/src/copy_blob_request_base.cpp
- azure-storage-cpp-lite/src/storage_credential.cpp
- blobfuse/blobfuse.cpp
>  Supporting blob-service SAS tokens

- blobfuse/fileapis.cpp
Fixed:
1. wrong logging of local file deletion status
2. fixed blob deletion status check
3. now azs_unlink will report an error if blob deletion actually failed
> Fixing blob deletion failure reporting

- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
Fixes compilation on my machine (as warnings are treated as errors)
> Fix catch value warning

- connectionGov.cfg
- connectionUSGov.cfg
I'll add some text in the wiki documentation to reference & explain this as well. Thank you for adding the Sovereign Cloud capability - I've had customers complain that the behavior for the blobEndpoint config is not well documented, so I'm attempting to flesh it out.
> Adding a sample AzureUSGovernment config file with blobEndpoint config example

- blobfuse/blobfuse.cpp
**What type of PR is this?**
/kind feature
**What this PR does / why we need it**:
This PR add `AZURE_BLOB_ENDPOINT` env to support different azure env
**Which issue(s) this PR fixes**:
Fixes #
**Special notes for your reviewer**:
**Release note**:
```
feat: add AZURE_BLOB_ENDPOINT env support
```
> feat: add AZURE_BLOB_ENDPOINT env support

- azure-storage-cpp-lite/include/executor.h
- azure-storage-cpp-lite/include/tinyxml2.h
- azure-storage-cpp-lite/src/tinyxml2.cpp
- azure-storage-cpp-lite/src/tinyxml2_parser.cpp
- blobfuse/tests.py
- test/cpplitetests.cpp
- Addressing fix for seg fault issue for running into accessing a null location
- updating tinyxml2 libaries
- reviewed by rickle
> Seg fault tinyxml fix addressing issue #249

- blobfuse/fileapis.cpp
> remove(3) returns 0 on success

- blobfuse/blobfuse.cpp
Attempting to resolve #233 with argument checking. This is a modification of blobfuse.cpp to validate the tmp-path inputs by using boost::filesystem::path to normalize the path (remove excess slashes, double-dot, and dot). We also add in an extra check for empty paths after the modifications to ensure it didn't resolve to root (/) or an empty path.
> Adding Boost Filesystem normalization to tmp-path [#233]

- .gitignore
- README.md
- azure-storage-cpp-lite/include/constants.dat
- azure-storage-cpp-lite/include/http/libcurl_http_client.h
- blobfuse/OAuthToken.cpp
- blobfuse/OAuthTokenCredentialManager.cpp
- blobfuse/OAuthTokenCredentialManager.h
- blobfuse/blobfuse.cpp
- blobfuse/blobfuse.h
- connection.cfg
This PR is in conjunction with MSI authentication, and commits including and past 63f791: "Support SPN based authentication" should be reviewed in this PR.
> Support Service Principal Name Authentication in blobfuse

- systemd/readme.md
- systemd/with-config-file/blobfuse.service
- systemd/with-config-file/readme.md
- systemd/without-config-file/blobfuse.service
- systemd/without-config-file/readme.md
Related to https://github.com/Azure/azure-storage-fuse/issues/347
> Systemd service file

- systemd/with-config-file/blobfuse.service
- systemd/without-config-file/blobfuse.service
> blog to blob, fixes #403

- CMakeLists.txt
- README.md
- blobfuse/blobfuse.cpp
- blobfuse/src/BlobfuseGlobals.cpp
- cpplite/include/http/libcurl_http_client.h
fixes to initialize curl http code and bump version.
> fixed curl initialization

- test/tests.py
Cache usage % check corrected, expect less or equal.
> Cache size check corrected

- blobfuse/generaterpm.sh
RPM build failure due to date format.
> RPM build failure due to invalid date format

- blobfuse-artifacts.yml
added task for codesign with esrp service connection
> added task EsrpCodeSigning for deb and rpm

- blobfuse/fileapis.cpp
- blobfuse/include/BlobfuseGlobals.h
- cpplite/src/utility.cpp
- test/feature_test.go
Revert single upload check. File name encoding sync with pre-1.3.1 level
> Revert single upload check. File name encoding sync with pre-1.3.1 level

- blobfuse/blobfuse.cpp
- cpplite/src/utility.cpp
> consolidated encodings and removed command line arg option

- blobfuse-nightly.yml
- blobfuse/src/DataLakeBfsClient.cpp
fixed spn auth for adls
added a nightly test case for adls account with spn auth
> fixed SPN and MSI auth for ADLS Gen 2

- blobfuse/src/BlobfuseConstants.cpp
- blobfuse/src/BlockBlobBfsClient.cpp
MSI download slowness due to improper parallelism fixed.
> Correcting parallelism factor for MSI

- README.md
- blobfuse-nightly.yml
- blobfuse/blobfuse.cpp
- blobfuse/include/BlobfuseGlobals.h
- cpplite/include/blob/create_block_blob_request.h
- cpplite/include/blob/put_block_list_request.h
- cpplite/src/blob/blob_client.cpp
- Populate content-type while uploading blob, based on file extension.
> Content-type can be updated based on file type using a cli option

- cpplite/adls/src/rename_file_request.cpp
- cpplite/include/storage_credential.h
- cpplite/src/storage_credential.cpp
- tools/generateSasForBlobfuse
Added a SAS generator CLI for blobfuse as the portal one does not work for chmod and mv
Added SAS token to x-ms-rename-header after the old filename
> got adls chmod and rename working

- .github/ISSUE_TEMPLATE.md
- .github/workflows/codeql-analysis.yml
- Small changes in Issue template
- Github was suggesting an action of code analysis using codeql to get some security related scans so added that as well.
> Adding issue template and code analysis github action

- blobfuse2-release.yaml
- common/types.go
Adding a stage in the release pipeline which will update the version number in the latestVersion.json file
> Auto update of version on release

- component/file_cache/file_cache.go
- If a file is readonly and file-cache decides to reload that file then it fails because read-only file can not be written
- fix for this is to change the mode and download and post download reset the mode
> Redownload of read-only file fix

- blobfuse2-release.yaml
- cmd/root.go
- common/version.go
- releaseVersionUpdate.py
- Have files with version name in the release container
- Checking the status code for existence of the warnings
- Updated the release pipeline to update the latest version file when we do a release
> Adding version and security warnings check

- component/azstorage/azauth.go
- component/azstorage/config.go
- component/azstorage/connection.go
- setup/baseConfig.yaml
Add a fileshare type to the config 
Tweak code to allow for creation of FileShare object
> File type setup

- common/util.go
- component/azstorage/block_blob.go
- component/stream/read_write.go
- component/stream/read_write_test.go
- component/stream/stream.go
- delay flush on appended data
- fixed nil pointer issue in pure streaming
- lock on stage+commit to avoid storage throwing on race
- added more tests
> Streaming small fixes and minor perf improvement

- README.md
Updating Readme to point to blobfuse2 code base and preview binaries.
> Update readme to point to v2

- TSG.md
Many similar contents to v1 TSG with minor edits. This is needed as our first iteration for the TSG to provide the docs team
> Blobfuse2 Starter TSG

- CHANGELOG.md
- cmd/mount.go
- cmd/mount_all.go
- component/attr_cache/attr_cache.go
- component/attr_cache/attr_cache_test.go
- component/azstorage/azstorage.go
- component/azstorage/block_blob_test.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- component/libfuse/libfuse.go
- component/libfuse/libfuse2_handler_test_wrapper.go
- component/libfuse/libfuse_handler_test_wrapper.go
- component/loopback/loopback_fs.go
- component/stream/read_test.go
- component/stream/stream.go
- internal/base_component.go
- internal/component.go
- internal/mock_component.go
- internal/pipeline.go
> Background auth validation fix

- CMakeLists.txt
- blobfuse-artifacts.yml
- blobfuse-nightly.yml
- blobfuse/include/AttrCacheBfsClient.h
- blobfuse/src/AttrCacheBfsClient.cpp
- blobfuse/src/BlockBlobBfsClient.cpp
- blobfuse/src/DataLakeBfsClient.cpp
- test/feature_test.go
1. Fixing v1 nightly pipeline failures
2. Fixing bug where empty directories are not getting deleted
3. Fixing bug: Marking directory as deleted for fsync directory
> Nightly pipeline fix

- azure-pipeline-templates/release-distro-tests.yml
- azure-pipeline-templates/verbose-tests.yml
- blobfuse2-release.yaml
- test/e2e_tests/dir_test.go
- Stablise artifact pipeline
- Add more test cases related to git status/stash, tar of directory
> Stablizing pipelines and adding more test cases

- blobfuse2-code-coverage.yaml
- cmd/secure_test.go
- common/config/keys_tree_test.go
- common/types.go
- common/util_test.go
- component/libfuse/libfuse_handler_test.go
Secure encrypt 
Mount with secure config
Removed some unused code in types
Encrypt, DecryptData functions
DirectoryEmpty function
Libfuse Default Permissions cases
> Miscellaneous Tests

- CHANGELOG.md
- component/azstorage/block_blob_test.go
- component/azstorage/config.go
- component/azstorage/datalake_test.go
- component/azstorage/utils_test.go
Resolves https://github.com/Azure/azure-storage-fuse/issues/894
> Fixed parsing of endpoint to support blob endpoints for ADLS accounts

- README.md
- sampleFileCacheConfig.yaml
- sampleFileCacheWithSASConfig.yaml
- sampleStreamingConfig.yaml
- setup/baseConfig.yaml
Resolves https://github.com/Azure/azure-storage-fuse/issues/935
> Document required config for azstorage + fix samples

- blobfuse2-perf.yaml
- component/azstorage/azauth_test.go
- component/azstorage/block_blob.go
- component/file_cache/lru_policy.go
- test/scripts/fio.sh
- FIO Random read/write test
- FIO CSI Driver test command (it has mix of rand read write operations and is time based)
- Make ResNet50 perf test based on flag (default enable)
> FIO Test additions

- azure-pipeline-templates/build-release.yml
- blobfuse2-release.yaml
1. Added block container parameter
2. Increased timeout
3. Changed VM to use Azure Pipelines VM instead of 1ES
> Fixed release pipeline UT

- CHANGELOG.md
- cmd/mount_all.go
- cmd/mount_test.go
- test/mount_test/mount_test.go
> Mount all fix

- CHANGELOG.md
- cmd/mount.go
> Updating umask value

- CHANGELOG.md
- cmd/mount.go
- cmd/mount_all.go
- cmd/mountv1.go
If version check fails to reach public container mount ./all/v1 command is exited
> If version check fails to reach public container mount ./all/v1 command is exited

- CHANGELOG.md
- cmd/mount.go
Create work dir if it does not exists
> Create work dir if it does not exists

- .github/CODEOWNERS
- CHANGELOG.md
- blobfuse2-code-coverage.yaml
- component/azstorage/azstorage.go
- component/azstorage/config.go
- component/azstorage/config_test.go
- component/azstorage/connection.go
- component/azstorage/utils.go
- setup/baseConfig.yaml
> Disable compression to be a configurable feature

- CHANGELOG.md
- component/attr_cache/attr_cache.go
- component/attr_cache/attr_cache_test.go
- component/azstorage/block_blob.go
- component/azstorage/config.go
- component/azstorage/config_test.go
- component/azstorage/connection.go
- component/libfuse/libfuse_handler.go
- main.go
- setup/baseConfig.yaml
This PR adds new configs to blobfuse which impacts list and open operation time
> Performance Improvements for blobfuse attribute lookup

- setup/blobfuse2.service
verified in systemd 249 (249.11-0ubuntu3.9)
> WorkingDirectory and User belong at Service level

- CHANGELOG.md
- README.md
- blobfuse2-code-coverage.yaml
- component/azstorage/azauthspn.go
- component/azstorage/config.go
> Fix resource string in SPN token generation

- .github/CODEOWNERS
- CHANGELOG.md
- component/file_cache/file_cache.go
> Create temp cach path recursively if it does not exists

- CHANGELOG.md
- setup/blobfuse2-logrotate
> Fixing log rotate script

- CHANGELOG.md
- azure-pipeline-templates/e2e-tests.yml
- blobfuse2-nightly.yaml
- cmd/health-monitor_stop_all.go
- cmd/unmount.go
- cmd/unmount_test.go
- component/azstorage/azauth_test.go
- component/file_cache/cache_policy.go
- component/file_cache/cache_policy_test.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- component/file_cache/lru_policy.go
- component/libfuse/libfuse.go
- tools/health-monitor/common/types.go
- if 'du' is not found, skip checking for disk usage in LRU policy
- for unmount check for fusermount3 rather then fusermount
- add more lru policy logs to detect why deletions are done
- v1 flag for file-cache-timeout-in-seconds is not honored while creating cache policy
> Multiple bug fixes

- blobfuse2-nightly.yaml
- blobfuse2-release.yaml
Adding image creation and testing for 
- Mariner 2
- RHEL 9
> RHEL 9 and Mariner 2 nightly test

- CHANGELOG.md
- cmd/mount.go
- common/types.go
- component/libfuse/libfuse.go
- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse_defs.h
- component/libfuse/libfuse_handler.go
- uid/gid supplied in config file are respected
- uid/gid supplied over cli params are getting overwritten by the current user and group info during config validation phase.
> Respect uid/gid sent over cli param or config file

- CHANGELOG.md
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
Fixes #1285
TODO: Will add tests
> Rename Directory fix in blob accounts

- component/azstorage/t2_azauth.go
- component/azstorage/t2_azauthmsi.go
- component/azstorage/t2_azauthspn.go
- component/azstorage/utils.go
TODO: testing will be done in some other PR
> Track2 Migration: Adding auth flows for SPN and MSI

- component/azstorage/azauth_test.go
- component/azstorage/azstorage.go
- component/azstorage/block_blob.go
- component/azstorage/config.go
- component/azstorage/config_test.go
- component/azstorage/connection.go
- component/azstorage/datalake.go
- component/azstorage/t2_azauth.go
- component/azstorage/t2_azauthkey.go
- component/azstorage/t2_azauthmsi.go
- component/azstorage/t2_azauthsas.go
- component/azstorage/t2_azauthspn.go
- component/azstorage/utils.go
- internal/attribute.go
- internal/component_options.go
This PR contains code for migrating block blob to use track2 azblob SDK.
NOTE: The tests migration will be done in some other PR.
> Track2 Migration: Block Blob migration

- blobfuse2-nightly.yaml
- component/azstorage/azauth_test.go
- component/azstorage/datalake.go
- component/azstorage/datalake_test.go
- go.mod
- go.sum
- Update azblob and azdatalake dependencies
- Enable Azurite tests
> Track2 Migration: Update SDK dependencies

- README.md
> Add mount all limitation

- CHANGELOG.md
- common/types.go
- common/version.go
- common/version_test.go
- component/azstorage/azstorage.go
- component/azstorage/utils.go
Also added dynamic update of SDK log listener on config change
> Track2 Migration: Updating version check logic for preview releases

- CHANGELOG.md
- component/azstorage/datalake.go
- component/azstorage/datalake_test.go
Added cpk support for datalake
> CPK support for datalake

- blobfuse2-release.yaml
- cmd/mount.go
- component/block_cache/block_cache.go
- component/libfuse/libfuse.go
Added code to display the entire mount command and fixed a spelling error.
> Display mount command

- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
Correct the Condition check that allows last block to be size greater than block size.
> Block cache openFile if condition bug

- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
Return error if a block to be overwritten fails to download
> Overwrite when download fails for the given block

- common/util_test.go
added code to delete the directory created after the test ends so the next iteration of tests doesn't fail
> Fix code coverage tests

- component/block_cache/block_cache.go
- exported/exported.go
- internal/component_options.go
Adding an exported package which allows internal package properties and methods to be exposed.
Exported package will be used for implementing custom components. This feature to add custom component will be added in the next PR.
> Exposing internal package for custom component feature

- cmd/health-monitor_test.go
- cmd/mountv1_test.go
- common/util_test.go
- component/azstorage/block_blob_test.go
- component/azstorage/datalake_test.go
- component/block_cache/block_cache_test.go
- component/entry_cache/entry_cache_test.go
- component/file_cache/file_cache_test.go
- test/e2e_tests/data_validation_test.go
- test/e2e_tests/dir_test.go
- test/e2e_tests/file_test.go
- test/stress_test/stress_test.go
Remove deprecated math/rand and iotuil methods.
> Remove deprecated methods

- cmd/mount.go
- cmd/mount_test.go
Fix the low coverage in mount.go
- [Pipeline run](<https://dev.azure.com/azstorage/BlobFuse/_build/results?buildId=23974&view=results>)
> Fix code coverage pipeline

- setup/packages.csv
Releasing in Debian 12 package
Adding Blobfuse2 support in Debian 12
> Adding Debian 12

- .github/workflows/codespell.yml
Code spell pipeline only runs when PR is created against main and not the feature branches.
Run code spell pipeline for PRs created against feature branches also.
Successful pipeline run for PR against `blobfuse/2.*` branches
> Run code spell pipeline for feature branch PRs

- .github/pull_request_template.md
Add more context to the PR template so that, nothing gets missed.
NA
NA
> Add more context to the PR template

- common/types.go
- component/xload/data_manager.go
- component/xload/data_manager_test.go
- component/xload/lister.go
- component/xload/splitter.go
- component/xload/splitter_test.go
- component/xload/stats_manager.go
- component/xload/stats_manager_test.go
- component/xload/utils.go
- component/xload/utils_test.go
- component/xload/xcomponent.go
- component/xload/xload.go
- component/xload/xload_test.go
Add unit tests for xload
In the CI and code coverage pipelines
> Xload: Unit tests

- .github/workflows/benchmark.yml
- perf_testing/scripts/fio_bench.sh
* Resolve the APT package manager Error
* [Temporary Fix] Clear the temp cache before mounting. as block cache sometimes don't clear the temp cache
> Get the Perf pipeline back

- .github/workflows/benchmark.yml
- perf_testing/scripts/fio_bench.sh
> Return true for the commands that were not important

- internal/dcache/metadata_manager/metadata_manager.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
> metadata singleton object

- .github/workflows/benchmark.yml
> Correct dispatch of workflow"

- NOTICE
- internal/dcache/rpc/gen-go/dcache/models/GoUnusedProtection__.go
- internal/dcache/rpc/gen-go/dcache/models/models-consts.go
- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/gen-go/dcache/service/GoUnusedProtection__.go
- internal/dcache/rpc/gen-go/dcache/service/chunk_service-remote/chunk_service-remote.go
- internal/dcache/rpc/gen-go/dcache/service/service-consts.go
- internal/dcache/rpc/gen-go/dcache/service/service.go
- internal/dcache/rpc/generate.sh
- Fix formatting of generated code using Thrift using `gofmt`
- Update the NOTICE file
Successful CI run
> Fix GO formatting for Thrift generated code and update NOTICE file

- .github/workflows/benchmark.yml
- blobfuse2-1es_ci.yaml
CI Pipeline using 1ES template for SFI resolution.
> 1ES PT CI pipeline

- .github/workflows/benchmark.yml
- azure-pipeline-templates/blobfuse2-ci-template.yml
- azure-pipeline-templates/build.yml
- blobfuse2-1es_ci.yaml
CI Pipeline migration to 1ES template.
> CI Pipeline 1ES migration

- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/rpc_test.go
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/server.go
- internal/dcache/rpc/server/utils.go
Initialize chunk service handler in RPC server
> RPC: Chunk Service handler initialization

- common/util.go
- component/distributed_cache/distributed_cache.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/cluster_manager/cluster_manager_impl.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/models.go
- internal/dcache/rpc/server/handler.go
Fix the typos detected by the codespell pipeline
> Spell checks

- internal/dcache/rpc/server/handler.go
Add reserved space for RV. This can be used to get the available space for the RV.
> RPC: Add reserved space for RV

- common/util.go
- internal/dcache/cluster_manager/cluster_manager_impl.go
- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/client/functions.go
Integration of RPC and replication manager with the cluster map.
> RPC: Integration with cluster map

- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/models.thrift
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/server.go
- internal/dcache/rpc/server/utils.go
- internal/dcache/rpc/utils.go
Refactoring of some methods in RPC package
> RPC: Refactoring

- component/distributed_cache/distributed_cache.go
- component/distributed_cache/utils.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/utils.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
- internal/dcache/models.go
> getattr and readdir changes for dcache files

- internal/dcache/metadata_manager/metadata_manager_impl.go
> Metadata manager audit.

- component/distributed_cache/distributed_cache.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/clustermap/utils.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/utils.go
- internal/dcache/models.go
> Few bug fixes

- internal/dcache/cluster_manager/cluster_manager.go
This first revision is refactoring to make the actual change easier.
> Adding fix-mv workflow

- component/distributed_cache/distributed_cache.go
- component/distributed_cache/utils.go
- component/libfuse/libfuse_handler.go
- component/libfuse/libfuse_wrapper.h
- internal/dcache/clustermap/utils.go
- internal/dcache/debug/callbacks.go
- internal/dcache/debug/debug_fs.go
- internal/dcache/models.go
- internal/handlemap/handle_map.go
- **Feature**: 
Support for debug capabilities in distributed cache
> Add debug Fs for debugging the dcache

- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
Changes to the StartSync and EndSync RPC calls.
> RPC: Start and End sync changes

- component/distributed_cache/distributed_cache.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/models.go
- internal/dcache/file_manager/utils.go
- internal/dcache/file_manager/worker.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
> Audit file manager package.

- component/distributed_cache/distributed_cache.go
- component/distributed_cache/utils.go
- internal/dcache/file_manager/worker.go
1. Support for Create dir
2.  Send partial write buffer for the last chunk
> Support Create dir in dcache

- component/distributed_cache/distributed_cache.go
- component/libfuse/libfuse_handler.go
- internal/dcache/file_manager/utils.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
- internal/dcache/rpc/server/handler.go
> callback changes

- component/distributed_cache/distributed_cache.go
- component/libfuse/libfuse.go
- component/libfuse/libfuse_handler.go
- internal/component_options.go
> streamdir changes for unqualified path

- component/distributed_cache/distributed_cache.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/clustermap/utils.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
> Safe startup, component RV matches and other fixes

- internal/dcache/rpc/client/functions.go
> Release rpc client in error path

- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/gen-go/dcache/service/service.go
- internal/dcache/rpc/models.thrift
- internal/dcache/rpc/response_error.go
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
- internal/dcache/rpc/service.thrift
Fixed the custom response error type returned in RPC response
> RPC: Custom RPC response error

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
- internal/dcache/models.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/response_error.go
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/utils.go
> More robustness fixes after extensive testing of various node up/down scenarios

- common/util.go
- component/distributed_cache/distributed_cache.go
- internal/pipeline.go
> Use block-cache while doing FS operations on Azure storage

- test/distributed_cache/test-cluster.sh
This script must be run from vm1, it'll perform various cluster operations and check validity after every step.
This is a WIP and needs to be extended.
> Automated cluster functionality validator

- common/error_inject.go
- common/log/logger.go
Subsequent changes will make use of these
> Adding basic error and sleep injection helpers

- internal/dcache/file_manager/buffer.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/models.go
- internal/dcache/file_manager/utils.go
- internal/dcache/file_manager/worker.go
- internal/dcache/replication_manager/models.go
- internal/dcache/replication_manager/replication_manager.go
> Improve Read Perf

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/rpc/server/handler.go
> Make joinmv idempotent, and other fixes

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/replication_manager/models.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/server/handler.go
> Reduce unncessary clustermap updates for better scalability and misc robustness fixes

- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/models.thrift
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/utils.go
> Add "removeAllChunks" option to the removeChunk RPC Request

- internal/dcache/clustermap/utils.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/utils.go
> Reduce logs while doing readahead

- component/attr_cache/attr_cache_test.go
> fix ut failing in pipeline 

- blobfuse2-release.yaml
> rhel install git fix in release pipeline

- go.mod
- go.sum
> Updating go dependencies

- component/azstorage/azstorage.go
- internal/component_options.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
> Few log fixes

- azure-pipeline-templates/data-integrity.yml
- azure-pipeline-templates/linux-git.yml
- blobfuse2-nightly.yaml
The following tests are added, 
* Compile linux source on the mountpoint
*  Git clone VScode, libfuse, blobfuse on the mountpoint
*  Build And Run Blobfuse on Blobfuse mountpoint
> Add New stage to the Nightly pipeline

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/debug/stats/stats.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
> Adding clustermanager stats

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/debug/stats/stats.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
> Fixed some stats to be more meaningful

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/debug/stats/stats.go
> Add heartbeat and other stats.

- component/azstorage/azstorage.go
> Don't auto-detect account if --use-adls flag is given 

- test/e2e_tests/dir_test.go
- test/e2e_tests/file_test.go
Add missing close calls in e2e tests that are failing some tests occassionally. lack of close calls is causing failure in the cleanup of the directory.
> fix e2e tests failure 

- TSG.md
> Document Blobfuse HTTPS communication and version check

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/server/handler.go
> Personal/linuxsmiths/more resilience using clustermap epoch (#1953)

- .github/workflows/ask_question.py
- .github/workflows/deepwikiaction.yml
New github action to post comment on incoming issues using DeepWiki research.
> Query DeepWiki with issue statement and post responce as comment

- internal/dcache/metadata_manager/metadata_manager_impl.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/server/handler.go
> Close channel before looping to avoid blocking

- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/client/client.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/client/functions.go
> rpc client bump to 256

- internal/dcache/file_manager/contiguity_tracker.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/utils.go
- internal/dcache/rpc/server/handler.go
> Do not upload more chunks if max unacked is greater than a fixed size

- component/distributed_cache/distributed_cache.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/utils.go
- internal/dcache/models.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/server/handler.go
> MV placement for reducing RV<->RV connections
