Azure/azure-storage-fuse

- azure-storage-cpp-lite/src/tinyxml2.cpp
> Suppress the fallthrough warnings

- README.md
- blobfuse/fileapis.cpp
- blobfuse/tests.py
- blobfuse/utilities.cpp
ensure_files_directory_exists_in_cache causes intermittent 'operation not permitted' issues when opening multiple files (10+) in parallel. Fix is to not error out when EEXIST is the error.
> Fixing failures due to EEXIST error from the cache dir

- blobfuse/utilities.cpp
It's possible to get an empty list of blobs and continuation token
> Fix situation when list blobs return an empty list and continuation token

- blobfuse/blobfuse.cpp
Fixes #66.
Normalizing tmp_path string in blobfuse.cpp so we don't need to check for a trailing slash all the time.
> Remove the traiiling slash in tmp_path

- azure-storage-cpp-lite/include/blob/blob_client.h
- azure-storage-cpp-lite/include/storage_account.h
- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
- azure-storage-cpp-lite/src/storage_account.cpp
- blobfuse/blobfuse.cpp
- blobfuse/blobfuse.h
Issue #22 - Adds support for non-public clouds via the use of account URI from connection.cfg
Here is connection.cfg template:
```
accountName myaccount
accountKey mykey==
containerName mycontainer
blobEndpoint myaccount.blob.core.windows.net
```
> Support for non-public clouds

- azure-storage-cpp-lite/include/blob/blob_client.h
- azure-storage-cpp-lite/include/constants.dat
- azure-storage-cpp-lite/include/get_blob_property_request_base.h
- azure-storage-cpp-lite/include/get_blob_request_base.h
- azure-storage-cpp-lite/src/blob/blob_client.cpp
- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
- blobfuse/blobfuse.cpp
- blobfuse/blobfuse.h
- blobfuse/directoryapis.cpp
- blobfuse/fileapis.cpp
- blobfuse/tests.py
- blobfuse/utilities.cpp
Addresses #95, #98, #99 
One caveat is that directory timestamps show the listing time (`now`) since there is no support for dirs in blob storage.
> Correct attributes:uid, gid and modified time

- azure-storage-cpp-lite/include/retry.h
With a max delay of 60s. All retries and delays included, a single operation should max out at about an hour.
> Exponential retries

- stresstests/README.md
- stresstests/Results/1.0.2_results.txt
- stresstests/blobfusestress.cpp
- stresstests/makefile
The is not meant to be the be-all end-all of stress & perf tests for blobfuse, but enough to get started and have a framework in place, that we can use to validate releases and build on to investigate future potential perf issues.
There is a lot of potential for improvements here for config (at the moment it's all hard-coded in code), when there's more time we should pull it out
> Perf & stress test

- CMakeLists.txt
- azure-storage-cpp-lite/CMakeLists.txt
Had already looked at standalone build of azure-storage-cpp-lite in #183 but found uuid dependency wasn't included at this level so would fail to build this target on ubuntu
> linking uuid library at client target level for standalone build

- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
Fix compilation error with GCC 8.2.1 :
> error: catching polymorphic type 'class std::exception' by value [-werror=catch-value=]
Compiled successfully after modification
> Fix by value exception catching

- README.md
- azure-storage-cpp-lite/include/executor.h
- blobfuse/blobfuse.cpp
- blobfuse/blobfuse.h
- blobfuse/fileapis.cpp
- blobfuse/tests.py
- blobfuse/utilities.cpp
- test/cpplitetests.cpp
- These changes are related to the changes sercan tried to submit in his pull request (#274)
- This change clears the cache after the high threshold is reached and will reduce the cache until it is below the low threshold. The cache still clears after the timeout.
- This change has already been reviewed by rickle and assorin
- This change also has the tests reformatted but for the most part unchanged aside from ordering and maintainability. There also have been test added for the gc cache threshold cleanup
> Gc cache threshold pr + test reformat

- blobfuse/blobfuse.cpp
This bug fix is for allowing non-fuse file systems to and blobfuse mount on the same directory.
> Mount directory can be mounted to other filesystem bug fix

- azure-storage-cpp-lite/include/blob/blob_client.h
- azure-storage-cpp-lite/include/blob/delete_blobdir_request.h
- azure-storage-cpp-lite/src/blob/blob_client.cpp
- azure-storage-cpp-lite/src/blob/blob_client_attr_cache_wrapper.cpp
- azure-storage-cpp-lite/src/blob/blob_client_wrapper.cpp
- blobfuse/blobfuse.cpp
- blobfuse/directoryapis.cpp
- test/attribcachesynchronizationtests.cpp
- test/attribcachetests.cpp
This PR has the following changes.
1) Directories are deleted along with directory markers so that blobfuse does not break ADLS.
2) For directory deletes there is no x-ms-header for snapshot [include or only] .
3) Test cases are also modified along to retrofit the changes.
Summary of my changes in this PR are 
created a new request header called delete_blobdir_request.h since the existing delete_blob_request.h was forcing either snapshot only or snapshot include x-ms-header. Directories have no snapshots so directory deletes were failing. 
In blob_client which is called by blob_client_wrapper and blob_client_attributecachewrapper I added a new method called delete_blobdir so that it uses the new delete_blobdir_request.h above.
In the directoryapis.cpp rmdir method I am calling this new …
> fix error where the ADLS directory cannot be deleted: prod bug

- systemd/without-config-file/blobfuse.service
According to [systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#%5BUnit%5D%20Section%20Options), `Description=` and `After=` settings should appear in the \[Unit\] section. Omitting section name leads to these log messages:
```
systemd[1]: /etc/systemd/system/blobfuse.service:1: Assignment outside of section. Ignoring.
systemd[1]: /etc/systemd/system/blobfuse.service:2: Assignment outside of section. Ignoring.
```
> Fix missing [Unit] section name

- README.md
I am proposing this change as the content didn't had any information on authType 'SPN' that we can use for Service Principal Authentication. The connection.cfg has details where it is mentioned that SPN should be used as authType. However, since README.md had no information provided on it, I have added those changes.
> Update README.md with authType SPN

- blobfuse-artifacts.yml
- blobfuse-nightly.yml
- blobfuse/include/DataLakeBfsClient.h
- blobfuse/src/DataLakeBfsClient.cpp
- if file/dir does not exists in local cache then even when rename is successful, on cli we return failure "Input/Output error"
> Rename in adls failing even after operation being sucessful

- README.md
- blobfuse/include/StorageBfsClientBase.h
- For Gen-2 accounts if ACL is set with mask and additional pricipals for a blob/container, file permissions are not shown correctly when mounted with blobfuse.
> Gen-2 ACL based blobs not showing correct permissions

- blobfuse-nightly.yml
This is required since these are causing a CLI prompt to be run in the pipelines that can not be auto accepted. This change is fine since the VM is static and the packages are already installed.
> Remove dependency installation

- component/azstorage/azstorage.go
Current we check against the capacity - this is problematic as libfuse create a slice with a capacity of the file size. What we need is the slice length
> [BUG] Check length of slice rather than capacity

- component/azstorage/datalake.go
Currently when a file is created it uses the dfs endpoint - this means we cannot use the blob endpoint for staging and committing. Now we create using block endpoint and just do a second call for ACLs.
> [BUG] Upload after creating does not work if > 256MB

- blobfuse-artifacts.yml
- blobfuse/directoryapis.cpp
- blobfuse/src/BlockBlobBfsClient.cpp
- blobfuse/src/DataLakeBfsClient.cpp
- blobfuse/utilities.cpp
In list-blob, get-attr and is-directory-empty checks blobfuse considers 404 as error while 403 status codes are retried. In most listing cases max retry of 20 is hard coded so if user does not have permission on a folder/file REST call will fail with 403 and blobfuse will always go in a loop of 20 retries affecting the performance of overall operation. As a fix to this it will now condifer 403 as non-retryable error and stop after first attempt.
> List blob retrying for 20 times even on 403 errors

- cmd/mount.go
- common/util.go
- component/file_cache/file_cache.go
- component/libfuse/libfuse.go
- component/loopback/loopback_fs.go
- component/stream/stream.go
- internal/pipeline.go
- With libfuse the signature in /etc/mtab has changed and code tuned for previous fuse driver is no more working now. So correcting the signature match for libfuse
- Some errors were not in the common format which are used across different components.
> Remount on same path is not failing

- cmd/mount.go
- component/azstorage/datalake.go
- component/azstorage/utils.go
- setup/baseConfig.yaml
…t ACL to preserve the existing principals added to the file
context:
In the portal if "Manage ACL" to any file/folder in container there are two things in it. One is regular Linux style triplet of 'rwx' and additionally you can provide specific access to various principals and identities as well. If we call SetACL it just overwrites all of them because we pass only the 'rwx' triplet and not the other principal related info. While we set permissions it just overwrites the triplets and leave the principals as is.
> chmod fix to preserve additional principals added to to ACL

- .gitignore
- common/lock_map.go
- component/file_cache/cache_policy.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- component/file_cache/lfu_policy.go
- component/file_cache/lru_policy.go
- component/stream/stream.go
- file-cache needed ex-locks on files before download or deletion
- these ex-locks works only when file has write permission
- to handle ex-lock and permission combination there was a lot of locks and complex logic involved in openFile. createFile and cache eviction logic
- Moving to a solution where open handle counter is maintained inside the file level locks and using those we take the ex locks.
> File-cache open-file complexity with respect to file locks removed

- blobfuse2-nightly.yaml
- blobfuse2-release.yaml
- test/csi_driver_test/Dockerfile
- tools/postinstall.sh
The postinstall script was generating various problems so we now default to ship the postinstall script in /usr/share/blobfuse2/
Fixes : #733
> Fixed bug where blobfuse2 could not be installed in docker container

- common/util.go
Let's say we mount an empty container using blobfuse2. Now if we try to remount it again on the same path, it should ideally throw an error. But if the path contains trailing '/', it doesn't. So, added a line where we trim the trailing '/' from the mount path.
> Fixed bug where remount on empty containers was not throwing error when the mount path has trailing '/'

- component/azstorage/azstorage.go
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
- component/azstorage/config.go
- component/azstorage/datalake_test.go
If the blocksize is not set - let's set it dynamically based on file size to avoid max blocks exceeded errors. 
changed default block size to 0.
> [BUG] Fixed block size max blocks exceeded bug when blocksize not set

- component/file_cache/lfu_policy.go
- component/file_cache/lru_policy.go
This will require some more thought into how to implement directory deletion properly. 
Note: This is fine to do temporarily for now since we already have a flaw in our logic where if we cache a file a/b/c/d/file.txt, then on close we will only delete directory d, leaving a/b/c still in the path. 
There is a race condition between https://github.com/Azure/azure-storage-fuse/blob/main/component/file_cache/lru_policy.go#L442 and https://github.com/Azure/azure-storage-fuse/blob/main/component/file_cache/file_cache.go#L728
OpenFile expects the directories to be present so we call MkDirAll. In between those two calls another CloseFile can come and cause that dir to be deleted
> Temporarily fixed fio error caused due to race condition between OpenFile and CloseFile

- common/log/base_logger.go
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
- While calculating block size we need to round off if blocksize*50K is not able to accommodate entire file.
- Add UT for block size
> Correction with Block Size calculation for upload 

- cpplite/src/blob/blob_client_wrapper.cpp
- In case of download flow, blobfuse divides file-size by number of parallel threads (default 12). In case file is very huge, for e.g. 120GB, then each thread is suppose to download 10GB data. 
- Once this work load division is done each thread just try to download this data in single request. As here data size is very huge server may timeout resulting into download failure
- Once work is distributed across parallel threads, each thread shall download one chunk at a time (~16MB) and continue untill designated workload is not complete.
> Fixing large download in single request issue

- cmd/mount_all.go
When we run mount all command, the --disable-version-check=true flag is added multiple times for subsequent containers. So, added a small fix where it is added only once.
> Adding disable version check flag only once when the mount all command is run

- component/file_cache/cache_policy.go
This resolves https://github.com/Azure/azure-storage-fuse/issues/784
some locales produce sizes of format `X,XM`
Replace `,` to `.`
> [BUG] ParseFloat fix for file cache on locales that provide a ","

- component/azstorage/file_share.go
- component/azstorage/utils.go
GetAttr(), Exists(), ListShares(), List()
> Files mvp interface methods

- NOTICE
- component/azstorage/azstorage.go
Adding code for blocking list calls for mounted directory based on block-list-on mount-sec variable set in config
> Block mounted directory list calls

- CMakeLists.txt
- blobfuse/directoryapis.cpp
- blobfuse/src/DataLakeBfsClient.cpp
- cpplite/include/constants.dat
Commands like "git stash" try attempting a non-empty directory. On regular filesystem it fails with error "directory on empty"
In case of blobfuse, for block blob account we check for non-empty directory condition but for gen2 account we go ahead and delete the directory recursively on container as well, this results into "git stash" command deleting ".git" directory and resulting into a corrupting git repository.
> Dont delete directory in case of gen2 account if directory is not empty

- CHANGELOG.md
- component/file_cache/file_cache.go
Commands like "git stash" try attempting a non-empty directory. On regular filesystem it fails with error "directory on empty"
In case of blobfuse, for block blob account we check for non-empty directory condition but for gen2 account we go ahead and delete the directory recursively on container as well, this results into "git stash" command deleting ".git" directory and resulting into a corrupting git repository.
In V2 we take decision based on local directory status. If local directory is empty then we allow deletion of directory. This is a wrong decision as local directory might be empty due to file-cache-eviction as well.
> V2 : Dont delete directory based on local cache status

- component/azstorage/file_share.go
- component/azstorage/file_share_test.go
+ basic testing in file_share_test.go
> File and dir setup methods 

- blobfuse/fileapis.cpp
in fileapis.cpp, storage_errno is assigned in an if statement, not compared against 404 (storage_errno is an int).
> remove assignment and add comparison to storage_errno

- azure-pipeline-templates/mount-test.yml
- cmd/health-monitor.go
- cmd/mount.go
- cmd/mountgen1.go
- cmd/mountgen1_test.go
- cmd/mountv1.go
- common/util.go
- common/util_test.go
- component/file_cache/file_cache.go
- test/mount_test/mount_test.go
Resolving a bug where the mount fails when we use tilde (~) character in the paths for mounted directory, config file or file cache path.
> Expand path

- component/azstorage/config.go
- component/azstorage/utils.go
- component/azstorage/utils_test.go
- auto detect auth mode if user has not given any mode on cli or config file
- based on other parameters detect the mode for e.g., if sas key is set then assume auth mode is sas.
> Auto detect auth mode if user has not provided it as config

- README.md
I found that
`https_proxy=http://172.10.10.10:8888 blobfuse2...`
did not work. Logs show `proxyconnect tcp: dial tcp: lookup http://172.10.10.10: no such host`
However this works: `https_proxy=172.10.10.10:8888 blobfuse2...`
So I'm offering this patch to the readme accordingly
> Change https_proxy / http_proxy example to a working example

- azure-pipeline-templates/distro-tests.yml
- azure-pipeline-templates/e2e-tests.yml
- blobfuse2-nightly.yaml
- test/e2e_tests/data_validation_test.go
- test/e2e_tests/dir_test.go
- test/e2e_tests/file_test.go
- testdata/config/azure_stream_direct.yaml
- testdata/config/azure_stream_filename_direct.yaml
1. stream with file handle
2. stream with file name
3. stream with file handle direct
4. stream with file name direct
We need 2 parameters quick test and stream direct since quick enables and disables data validation and stream direct just disables certain large tests that take too much time
Successful run https://dev.azure.com/azstorage/BlobFuse/_build/results?buildId=14710&view=logs&jobId=b5bd9172-90ea-50d8-60e0-1bcee2c00945
> Added stream data validation test cases

- test/e2e_tests/data_validation_test.go
Test case takes too long, so we will rely on small files for data validation for stream direct case.
> Fix line to disable medium file for stream direct

- blobfuse/src/BlobStreamer.cpp
Hi Blobfuse team,
Found a case that might be missed: 
when calling `BlobStreamer::GetBlock` if `start_offset `> `obj->GetSize()`, `download_size `will get a maximum of `download_size`'s type.
Like when `block_size` equals 512 * 1024 * 1024, `offset` equals 512 * 1024 * 1024 + 100, `obj->GetSize()` equals 10. 
`start_offset ` will get 512 * 1024 * 1024 - 100 and it gonna execute` download_size = obj->GetSize() - start_offset;` .`obj->GetSize() - start_offset` logically would get negative. 
But, if we assign the negative value to `download_size `of type uint64_t, `download_size ` will be converted to UINT64_MAX. 
I think this should be an unexpected behavior. The risk of memory leak might incur security issues.
I hope it helps thx,
jack
> [fixed] unexpected maximum might incur security issues.

- CHANGELOG.md
- azure-pipeline-templates/mount-test.yml
- azure-pipeline-templates/verbose-tests.yml
- blobfuse2-nightly.yaml
- component/libfuse/libfuse.go
- component/libfuse/libfuse_handler_test.go
- component/libfuse/libfuse_handler_test_wrapper.go
- setup/baseConfig.yaml
- test/mount_test/mount_test.go
Fixes #1015 
By default, on fuse3 we enable write-back-cache at kernel level. To populate kernel cache, kernel issues a read command on your file. Now assume you opened a file handle in WRONLY or APPEND mode, which means handle does not have read permissions. When kernel tries to read file using such handle the read operation fails and in turn users' Open operation returns back with error. To fix this (as write-back-cache boosts performance) we added a flag to ignore the open flag. This means even if user opens a file in write/append mode we always add read permissions as well.
So, if you are not able to open a file in write only or append only mode but want to use cache you need to now give ignore-open-flags=true always. Otherwise disable the write-back cache. We made this a configurable …
> Set ignore-open-flags to true by default

- .gitignore
- CHANGELOG.md
- TSG.md
- cmd/mount.go
- cmd/mount_test.go
- cmd/secure.go
- common/log/logger.go
- common/util.go
- common/util_test.go
- tools/health-monitor/main.go
- If user does not have a home directory, blobfuse panics
- When user provides "default-working-dir" it is not honored while defining default logging path
- At init time default logging is set to syslog, still blobfuse tries to create a directory under user home directory for logs.
- Mount path or logging path with any environment variable set fails. e.g. mountpath: $HOME/abc
> Fix Panic generated when user does not have a home directory set

- CHANGELOG.md
- cmd/mount.go
- cmd/mount_test.go
- component/libfuse/libfuse.go
> Exit with non-zero status code if allow_other is used but not enabled in fuse config

- CHANGELOG.md
- README.md
- component/file_cache/file_cache.go
- setup/baseConfig.yaml
--sync-to-flush added new flag to control this behaviour
> sync call can force upload a file to storage if configured

- CHANGELOG.md
- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse2_handler_test_wrapper.go
- component/libfuse/libfuse_handler.go
- component/libfuse/libfuse_handler_test_wrapper.go
#1102 : ignore nsec from file times.
> fix for #1102

- CHANGELOG.md
- azure-pipeline-templates/verbose-tests.yml
- cmd/mount.go
- cmd/mount_test.go
- component/libfuse/libfuse.go
- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse_handler.go
- component/libfuse/libfuse_handler_test.go
- setup/baseConfig.yaml
- test/e2e_tests/file_test.go
- testdata/config/azure_key_directio.yaml
direct_io can be used to bypass the kernel cache. It disables the use of page cache in the kernel.
TODO: add this option for fuse2.
> Adding FUSE option direct_io

- CHANGELOG.md
- component/azstorage/block_blob.go
- component/azstorage/datalake.go
- component/azstorage/utils.go
- component/file_cache/file_cache.go
- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse_handler.go
- Added error log in `newBlobfuse2HTTPClientFactory`. Fixes #1161.
- Return `C.EACCES` error from libfuse in case of AuthorizationPermissionMismatch error from azstorage.
> Auth permission mismatch error check from azstorage

- cmd/mount_test.go
- component/libfuse/libfuse.go
Earlier if the config file given by the user had any other component except "libfuse" as the first component, blobfuse2 still successfully mounted the user's container. This behaviour was not desired. 
I made the required changes for libfuse to have highest priority in the component list. This will fix this issue.
> Fixed the priority level of libfuse

- CHANGELOG.md
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- As file is renamed the destination file remains in file-cache. This file is not added to LRU because it was never opened or closed hence policy will never delete this file.
- As a Fix add the destination file to policy after successful rename,
> Rename leaving destination file in temp-cache for ever

- CHANGELOG.md
- common/types.go
- component/azstorage/azauthmsi.go
- component/loopback/loopback_fs.go
- go.mod
- go.sum
- internal/base_component.go
- internal/component.go
- internal/mock_component.go
- Refer to AzCopy private branch where
-  Rename API works with delegation sas
- SAS token is redacted from x-ms-rename-source header
- msi allows custom endpoint to fetch token
- Allow user to configure custome msi-endpoint using env variable
> Multiple Bug fixes

- go.mod
- go.sum
Fixed the log redaction for `x-ms-rename-source` request header.
This PR only updates the AzCopy dependency. The actual changes can be found in [this](https://github.com/Azure/azure-storage-azcopy/commit/787a98b9a2b1f060d879f88e0d8bae97bbe38f1b) commit.
> Rename file and directory fix in ADLS accounts

- CHANGELOG.md
- azure-pipeline-templates/e2e-tests-spcl.yml
- azure-pipeline-templates/e2e-tests.yml
- azure-pipeline-templates/verbose-tests.yml
- component/azstorage/block_blob.go
- component/azstorage/config.go
- component/azstorage/connection.go
- component/azstorage/datalake.go
- component/libfuse/libfuse_handler.go
- setup/baseConfig.yaml
- test/e2e_tests/dir_test.go
- test/e2e_tests/file_test.go
- testdata/config/azure_key_symlink.yaml
Fixes #1243
- In ADLS accounts, read symlink fails after dir list operation. This is because the ADLS List API does not return metadata and other properties in its response (unlike blob API which does).
- To get the metadata, GetProperties() call is explicitly made after the List() operation for each blob.
- To enable symlink support in ADLS accounts, either pass `--no-symlinks=false` in the mount command or set `no-symlinks: false` in the config under attr_cache section.
> Symlink fix for ADLS accounts

- CHANGELOG.md
- common/types.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- test/scripts/fsync_sample.c
sync-to-flush flag is suppose to fore upload a file to container. In previous fix it was just setting the dirty flag, which will upload the file only on close. Corrected the code to force upload the file on sync itself.
> Correcting sync to flush behavior

- CHANGELOG.md
- common/types.go
- component/attr_cache/attr_cache.go
- component/azstorage/datalake.go
- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse_handler.go
- Get stat of a directory not present in the storage account
- Create the directory using Azure portal
- Run mkdir command -> Attribute cache will now invalidate the entry of the directory if it gets `PathAlreadyExists` error
- Create file inside the directory
**NOTE:** When directory is created using some other process (not blobfuse), then `negative-entry-expiration-sec` parameter in libfuse component must be set to 0 to disable kernel caching.
> Attribute cache invalidation on PathAlreadyExists error

- component/azstorage/azauthmsi.go
Fix `expiresOn` being defaulted to `1969-12-31 23:00:00 +0000 UTC` instead of the correct expiration time, as described on #1326
> Fix expiresOn on MSI auth when fetching token from CLI

- component/azstorage/azauthmsi.go
- component/azstorage/azauthspn.go
Currently the code in `component/azstorage/azauthmsi.go` logs sensitive data such as access tokens in the `log.Info` level, which can lead to sensitive data being present in the logs.
As having the access tokens can be useful for debugging, I'd like to propose this format, where the information that the token was successfully retrieved is logged in the `Info` level, but the token itself only in the `Debug` level.
> Make logging of credentials in azauthmsi.go and azauthspn.go consistent

- CHANGELOG.md
- component/libfuse/libfuse_handler.go
- component/libfuse/libfuse_wrapper.h
> libfuse-3.3 does not support 1MB max_write

- CHANGELOG.md
- README.md
- azure-pipeline-templates/blobfuse2-ci-template.yml
- cmd/mount.go
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- component/stream/read_write.go
- component/stream/read_write_filename.go
- go_installer.sh
- internal/component_options.go
- Close and flush will return immediately when lazy-write is enabled and upload of dirty file will be scheduled
- File will be locked till upload is in progress and no new handle for the same file can be created during this time
- Before unmount ensure all downloads are complete
> Add lazy-write feature to make flush and close async in nature.

- CHANGELOG.md
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
- Get atrribute for directory file is failing when CPK is enabled as ListBlob  API does not return the metadata when the blob is encrypted [https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs](url)
- So fetching the metadata for encrypted blobs explicitly using get properties rest api [https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob-properties](url)
> Get attribute fix for directory with cpk enabled

- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse_handler.go
Correct error code from EIO to EACCESS when creation of file fails due to insufficient permissions
> Create File error code correction for SAS on ADLS

- CHANGELOG.md
- component/block_cache/block_cache.go
- component/block_cache/blockpool.go
- component/block_cache/blockpool_test.go
Reset the block data to null when it is released back to the block pool. As a result of this, a block retrieved from the block pool will have null data instead of garbage data.
> Reset block when released

- CHANGELOG.md
- azure-pipeline-templates/cleanup.yml
- azure-pipeline-templates/e2e-tests-block-cache.yml
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
- component/block_cache/blockpool_test.go
- testdata/config/azure_block_perf.yaml
- testdata/config/azure_key_bc.yaml
Random write operations in block cache will be disabled by default. It can be enabled by passing the CLI flag `--block-cache-enable-random-write` in the mount command.
This PR also checks and returns error in the following cases:
1. Race condition between uploading and writing to a same block.
2. Random write scenario where a block has been staged and cleared from the in-memory cache and write call comes for that block.
3. A staged block (not last block) has data less than the block size.
The fixes for the above will be done in future PRs.
> Block cache disable random write

- CHANGELOG.md
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
- Do not delete blocks on sync/flush and preserve them for later usage.
- Delete them only when file is closed.
> Preserve blocks on flush 

- CHANGELOG.md
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
- testdata/config/azure_block_perf.yaml
Removed the flag which was disabling random write operations in block cache
> Enabling random write in block cache

- CHANGELOG.md
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
If write request comes for a block which has been staged (uncommitted) and deleted from the buffer list, then
- Stage the existing dirty blocks
- Commit the staged blocks via PutBlockList
- Download the given block for which the write request has come
> Updating an uncommitted block which has been deleted from buffer cache

- CHANGELOG.md
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
Return error if a block which is to be overwritten, fails to download.
> Check download status before overwriting a block

- CHANGELOG.md
- azure-pipeline-templates/verbose-tests.yml
- cmd/health-monitor.go
- cmd/mount.go
- component/azstorage/azauthmsi.go
- component/block_cache/block.go
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
- component/block_cache/block_test.go
If read request comes for a block which has been staged (uncommitted) and deleted from the buffer list, then
- Stage the existing dirty blocks
- Commit the staged blocks via PutBlockList
- Download the given block for which the read request has come
This also applies during prefetching a block which is uncommitted and has been cleared from the buffer list.
> Reading an uncommitted block which has been deleted from buffer cache

- CHANGELOG.md
- cmd/health-monitor.go
- cmd/mount.go
- component/azstorage/azauthmsi.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
Fixed File Cache failed to upload if Read perm is not given by changing file perm to read and resetting it after upload.
> File Cache failed to upload if Read perm is not given 

- component/block_cache/block_cache.go
- test/e2e_tests/data_validation_test.go
Issue: https://github.com/Azure/azure-storage-fuse/issues/1426
Closing the channel twice causing the panic.
This can happen in 3 scenarios:
1. Closing the file.
2. when requesting a block for writing.
3. Evicting the blocks when the file is in rand-read mode.
Both call the same method waitAndFreeUploadedBlocks, which unblocks the requested no of blocks inside the cooked list. but cooked list might contain the blocks which were unblocked already (i.e., when blocks are downloaded they were moved to cooked list when there is a reader for them and unblocked), hence calling unblock on them again causes panic.
> panic on calling close on close channel

- CHANGELOG.md
- azure-pipeline-templates/e2e-tests-block-cache-data-integrity.yml
- component/block_cache/block.go
- component/block_cache/block_cache.go
- component/block_cache/block_test.go
- test/e2e_tests/data_validation_test.go
https://github.com/Azure/azure-storage-fuse/issues/1426
Read is getting panicked due to block.endIndex being incorrectly modified.
**Fix:**
Removed block.endIndex field and added a simple way to find the block size.
> Fix ReadPanic

- component/block_cache/block_cache_test.go
UT in Rocky env is failing due to insufficient memory.
Available memory on the system is low.
Reduce the amount of memory needed by UT and validate it works.
NA
> Rocky UT fails due to insufficient memory

- CHANGELOG.md
- README.md
Readme updates as per PM comments for the 2.4.0 release.
Readme updates as per PM comments for the 2.4.0 release.
> Readme updates for 2.4.0 release

- CHANGELOG.md
- common/types.go
- component/azstorage/azauth.go
- component/azstorage/config_test.go
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
Moved the block pool and thread pool creation code from `Configure()` to `Start()` method, so that it is created only once in the child process.
`Configure()` method is called twice both in parent and child process. As a result of this block pool and thread pool were created twice resulting in higher memory utilization. So, moved the code to `Start()` method which is called only once in the child process.
Can be verified from the logs.
> Create block pool only once in child process

- CHANGELOG.md
- cmd/mount.go
File-cache as a flag `cleanup-on-start`. After an ungraceful unmount, next mount shall wipeout the cache only if this flag is set otherwise cache shall be reused.
Flag is checked incorrectly and it wipes out cache even when flag is set to false.
Mount, read a file, crash, restart and the tempcache shall not cleanup on mount,
NA
> After an ungraceful unmount, mount shall cleanup temp-cache only if flag is set

- common/types.go
- common/util.go
- common/util_test.go
In case of mount all or while mounting Azure special container like "$web", expandPath assumes it's an enviornment variable and tries to expand it while it shall skip these special container names. As part of this change we will not expand any environment variable in any path or config file name if env variable name matches reserved Azure Container name.
UT has been added and related bug has been linked.
NA
> In case of mount and mount all, if the container name has '$' do not treat it as env variable

- CHANGELOG.md
- README.md
- blobfuse2-code-coverage.yaml
- component/azstorage/azauth.go
- component/azstorage/azauthWorkloadIdentity.go
- component/azstorage/config.go
- [ x] New feature
Renaming ClientAssertion to WorkloadIdentity. Workload Identity was built initially for AKS and GitHub to get an app token using identities minted within the cluster itself. This capability has now been extended to support managed identities directly, so the name workloadidentity is a better fit.
Manual Testing
NA
> Rename ClientAssertion to WorkloadIdentity

- component/azstorage/azstorage.go
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
- component/azstorage/datalake.go
- component/azstorage/datalake_test.go
- **Improvement**: (Brief description of the feature or issue being addressed)
Display the detailed error if the mount fails
Ex: if the container dont exists, while mounting:
**Before change**: 
Error: failed to authenticate credentials for azstorage
**After change**:
Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage, [BlockBlob: [ContainerNotFound]]]
Error: failed to initialize new pipeline [failed to authenticate credentials for azstorage, [Datalake: [FilesystemNotFound]]]
UT's are included
- [Issues](<https://github.com/Azure/azure-storage-fuse/issues/1647>)
> return the detailed error when the connection fails

- common/util.go
- common/util_test.go
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
- component/azstorage/utils.go
- component/azstorage/utils_test.go
- component/loopback/loopback_fs.go
- component/xload/data_manager.go
- component/xload/data_manager_test.go
- component/xload/lister.go
- component/xload/lister_test.go
- component/xload/splitter.go
- component/xload/splitter_test.go
- component/xload/utils.go
- component/xload/xload.go
- component/xload/xload_test.go
Add consistency check on download of blob. After download is complete, md5sum of the local file is computed and compared with the md5sum of the blob, if it is set on the blob.
Added unit tests
> Xload: Add consistency check

- CHANGELOG.md
- cmd/mount.go
- cmd/mountv1_test.go
- cmd/unmount.go
- cmd/unmount_all.go
- cmd/unmount_test.go
This PR adds a new flag to the unmount command `lazy` which will pass the lazy flag to fusermount when unmounting. This enables unmount the mount when the device or resource is busy. fusermount will unmount once the device is no longer busy, making it easier to unmount existing mounts.
Added unit tests for new flag as well as manual testing of the new `lazy` flag.
- [Issues](https://github.com/Azure/azure-storage-fuse/issues/797)
> Feature: Lazy unmount

- cmd/mount.go
- component/libfuse/libfuse.go
- component/libfuse/libfuse_handler_test.go
- **Bug Fix**: (Brief description of the feature or issue being addressed)
/tmp folder is getting full due to the space used by the deleted file /tmp/blobfuse2.pid when the fuse-trace option is enabled and mounted without foreground option. 
**Reason:**
Currently we use stdout for emitting the libfuse logs. Now when user don't use foreground option while mounting, generally the mounted process have its stdout and stderr linked to the file /tmp/blobfuse2.log so these logs are redirected to that file. But this file is deleted by the parent process after the mount become successful. so now this is a deleted file with an open file descriptor. Size of this file gets bigger and bigger until user unmounts. sad part is user cannot delete this file as it's already deleted by the parent process of …
> Fix logs using up all the space of /tmp folder

- component/distributed_cache/utils.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
The name "cache-object-length" is not compatible with naming system that is followed by azure storage for names used in the metadata fields. [See here](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#metadata-key-and-value-names) 
Hence using cache_object_length as new metadata field.
> Change size property for metadata files in dcache

- internal/dcache/rpc/server/handler.go
Fix the race condition between chunk IO (get, put or remove chunk) and sync (start or end sync) operations. Sync operation will wait for ongoing IO operations to complete and will block new IO operations.
> RPC: Fix race condition between chunk IO and sync operations

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
Now we clear the cluster ReadOnly status when number of nodes that have joined the cluster goes more than MinNodes config.
> Add support for MinNodes config.

- component/libfuse/libfuse_handler.go
> Disable readahead capability for FUSE

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
Currentl we are limiting total MVs by this calculation
maxMVsPossible := (len(rvMap) * MvsPerRv) / NumReplicas
We are also counting offline MVs, which do not consume any RVs, so we are limiting our MVs to a smaller value.
This changes fixes it to only count usable MVs (which are not offline)
> Don't count offline MVs towards usable MVs

- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/client/functions.go
- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/gen-go/dcache/service/chunk_service-remote/chunk_service-remote.go
- internal/dcache/rpc/gen-go/dcache/service/service.go
- internal/dcache/rpc/models.thrift
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
- internal/dcache/rpc/service.thrift
- internal/dcache/rpc/utils.go
Added GetMVSize() RPC API to get the size of the MV while running the fix MV workflow.
> RPC: Added GetMVSize() API

- internal/dcache/replication_manager/models.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/replication_manager/utils.go
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
Remove the sync MV directory dependency in StartSync, EndSync and PutChunk (both client and sync writes) RPC calls. All chunks will be written inside the RV/MV directory.
> Remove sync MV directory

- internal/dcache/debug/callbacks.go
- internal/dcache/debug/debug_fs.go
This will return the last-updated-at field in clusetermap as atime, mtime, ctime and also file perm as 0444
> Return correct permission and times in stat for clustermap proc file

- component/azstorage/azstorage.go
- component/azstorage/block_blob.go
- component/azstorage/block_blob_test.go
- component/azstorage/connection.go
- component/azstorage/datalake.go
- component/azstorage/datalake_test.go
- component/distributed_cache/storage_callback_impl.go
- internal/base_component.go
- internal/component.go
- internal/component_options.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
- internal/dcache/storage_callbacks.go
- internal/mock_component.go
- support for rename-no-replace in fns and hns acnts
- support for returning etag in writeBuffer API, needed this etag to optimize some REST api calls.
> Az storage changes for dcache

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/models.thrift
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/utils.go
Add `MaybeOverwrite` field in PutChunk request to let the server that this request could potentially be an overwrite of a chunk that we previously wrote, so that it relaxes it's overwrite checks.
This PR also sets the `ReserveSpace` field in JoinMV request in fix-mv workflow.
> Add MaybeOverwrite field in PutChunk request

- blobfuse2-release.yaml
- setup/packages.csv
By default both preview and GA binaries go with the same package name "blobfuse2". This means if a customer tries to install the latest version, they may end up installing a preview version. We want all out customers to by default have a GA version and make a concious choice to install preview binary explicitly. To do so we are renaming our package for preview binaries to "blobfuse2-preview".
> Preview binaries shall go with a different package name

- component/distributed_cache/distributed_cache.go
- component/distributed_cache/distributed_cache_test.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap_dummy_success.json
- internal/dcache/clustermap/utils.go
- internal/dcache/models.go
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
Currently we have mvs-per-rv which is more complex for the user to understand. User can easily express his cluster size in terms of max nodes and hence max RVs (as he will know how many RVs per node). Then we can calculate MVsPerRV accordingly.
We don't want to make too many MVs, but enough to get a decent distribution of file chunks across RVs.
> Add max-rvs config for user to specify the cluster size.

- cmd/mount.go
- cmd/mount_test.go
If direct-io was set in the config file, then it was not removing the attr_cache correctly from the components slice.
Added UT.
> Fix when direct-io is enabled in the config file

- .gitignore
- component/distributed_cache/parallel_writer.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/models.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/server/handler.go
Currently a new node that starts up adds its RVs to the clustermap before it can proceed. Every node does it for their RVs and they have to claim ownership on clustermap before they can do it. With large number of nodes, this serial process takes lot of time. Practically observed one node every half a second. So for 10K nodes, this will take 5000 secs. This is not acceptable.
This change improves it by letting one node add new RVs for multiple nodes, this reducing the changes needed to clustermap and thus the time.
> Make adding myRVs to clustermap more efficient.

- component/distributed_cache/distributed_cache.go
- internal/dcache/buffer.go
- internal/dcache/file_manager/file_manager.go
- internal/dcache/file_manager/utils.go
- internal/dcache/file_manager/worker.go
- internal/dcache/replication_manager/models.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/gen-go/dcache/models/models.go
- internal/dcache/rpc/models.thrift
- internal/dcache/rpc/server/handler.go
- internal/dcache/rpc/server/utils.go
Total Allocations came down while using dcache with 1 replica in 1 node, where entire data of the file is served from local node.
```
|---------------+-------------------|
| Before change | Total Allocs      |
|---------------+-------------------|
| WRITE 10G     | 1297115616(1.2G)  |
| READ 10G      | 11957655696(11.9G) |
|---------------+-------------------|
|--------------+-------------------|
| After change | Total Allocs      |
|--------------+-------------------|
| WRITE 10G    | 1121690104(1.12G) |
| READ 10G     | 1130115944(1.13G) |
|--------------+-------------------|
```
> Allocate buffer from BufferPool while reading from the Local RV

- blobfuse2-release.yaml
Migrate the ESRP code signing and PMC publish workflows to use MI based approach using WIF.
Tested using the release pipeline.
> ESRP and PMC migration to MI

- testdata/config/azure_key.yaml
…pipeline
Increase file cache size in the config file due to the recent [change ](https://github.com/Azure/azure-storage-fuse/pull/1870)where cache size is treated as the hard limit and fail the read/write operations with IO error in config file. To prevent this file cache size is increased from 2G->20G. The maximum file size used in the tests is 10G.
> Increase file cache size limit in config file.

- component/azstorage/azstorage.go
- component/azstorage/block_blob_test.go
- component/azstorage/datalake_test.go
- component/block_cache/block_cache.go
- component/block_cache/block_cache_test.go
- component/file_cache/file_cache.go
- component/file_cache/file_cache_test.go
- component/libfuse/libfuse2_handler.go
- component/libfuse/libfuse_handler.go
- component/loopback/loopback_fs.go
- component/loopback/loopback_fs_test.go
- component/xload/data_manager.go
- internal/base_component.go
- internal/component.go
- internal/mock_component.go
convert read options struct to pointer in the pipeline.
```
type ReadInBufferOptions struct {
Handle *handlemap.Handle
Offset int64
Etag   *string
Data   []byte
Path   string
Size   int64
}
```
The above struct takes 74 bytes, we don't want to do copy of this struct across the pipeline for every readcall. As the read operations were very frequent. This cause some performance penality.
Currently we do 3 copies of this struct for every read call, if we have the pipeline as libfuse->block_cache->attr_cache->azstorage
> Convert read options struct to pointer in the pipeline

- common/assert.go
- common/util.go
- component/distributed_cache/distributed_cache.go
- component/distributed_cache/utils.go
- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/clustermap/clustermap_dummy_success.json
- internal/dcache/clustermap/utils.go
- internal/dcache/debug/stats/stats.go
- internal/dcache/metadata_manager/metadata_manager_impl.go
- internal/dcache/models.go
- internal/dcache/rpc/server/handler.go
Fault domain may or may not be available for an RV. If available we honor it and do not pick multiple component RVs of an MV from the same fault domain. If fault domain is not available for an RV it can be used for pplacing any MV. This way we work well w/ and w/o fault domain info for RVs.
This change itself doesn't add support to query fault domain from IMDS endpoint.
This also updates the placer so that it tries to distribute MVs uniformly across various RVs picking RVs which are free over RVs which are fuller.
- [] Bug fix
> Update MV placer to honor fault domains when choosing component RVs, and many other scale and correctness fixes

- internal/dcache/cluster_manager/cluster_manager.go
- internal/dcache/clustermap/clustermap.go
- internal/dcache/replication_manager/models.go
- internal/dcache/replication_manager/replication_manager.go
- internal/dcache/rpc/client/client_pool.go
- internal/dcache/rpc/server/handler.go
currently copyOutOfSyncChunks() copies one chunk at a time, resulting in low resync throughput. This change copies 16 chunks parallely.
> Perform sync of more than one chunk in parallel, to speed up resync jobs
